version: 2
jobs: 
  build: 
    macos:
      xcode: "10.2.1"
    steps:
      - checkout
      - run:
          name: Fetching CocoaPods Specs...
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run:
          name: Installing Pods...
          command: pod install
      - run:
          name: Decoding Mac Developer Certificate...
          command: fastlane prepare_certificates  
      - run:
          name: Building Pock...
          command: xcodebuild -workspace Pock.xcworkspace -scheme Pock -configuration Debug -derivedDataPath Artifacts
      - run:
          name: Moving Pock...
          command: mv ./Artifacts/Build/Products/Debug/Pock.app ./Pock.app
      - run:
          name: Compressing Pock....
          command: zip -r pock.zip ./Pock.app
      - store_artifacts:
          path: pock.zip
          destination: pock
